name = "aoc_practice"
description = "Learning Ada through Advent of Code challenges"
version = "0.1.0-dev"

authors = ["Clark Hoffman"]
maintainers = ["Clark Hoffman <cch952@usask.ca>"]
maintainers-logins = ["Spilskinanke"]

executables = ["aoc_practice"]
